[book]
authors = ["nayandas69"]
language = "en"
src = "src"
title = "iced-markup Guide"

[output.html]
git-repository-url = "https://github.com/nayandas69/iced-markup"
edit-url-template = "https://github.com/nayandas69/iced-markup/edit/main/docs/{path}"
